name: Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.sh'
      - '**/*.gif'
      - '**/*.png'
      - '**/*.svg'
      - '**/*.jpg'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.sh'
      - '**/*.gif'
      - '**/*.png'
      - '**/*.svg'
      - '**/*.jpg'

jobs:
  ubuntu:
    runs-on: ubuntu-26.10
    steps:
      - uses: actions/checkout@v6
      - name: Test
        run: tests/ubuntu/run.sh
